apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bim-schedule-website
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bim-schedule-website
  template:
    metadata:
      labels:
        name: bim-schedule-website
        app: bim-schedule-website
    spec:
      containers:
      - image: registry.cn-beijing.aliyuncs.com/huazhu_alpha/bim-schedule-website:${TAG}
        imagePullPolicy: Always
        name: bim-schedule-website
        ports:
        - containerPort: 8080
